{
 "title": "Energy",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Temps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (hass_sensor_temperature_celsius{friendly_name=\"Living Room Temperature\"}) * 1.8 + 32",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(friendly_name) (hass_sensor_temperature_celsius{friendly_name=\"Upstairs Temperature\"}) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (hass_sensor_humidity_percent{friendly_name=\"Living Room Humidity\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(friendly_name) (hass_sensor_humidity_percent{friendly_name=\"Upstairs Humidity\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Living room thermostat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (hass_sensor_temperature_celsius{friendly_name=\"Living Room Temperature\"}) * 1.8 + 32",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "hass_sensor_temperature_celsius{friendly_name=\"OpenWeatherMap Temperature\"} * 1.8 + 32",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "sum by(friendly_name) (hass_climate_target_temperature_high_celsius{friendly_name=\"Living Room\"}) * 1.8 + 32",
     "legendFormat": "Target temp high"
    },
    {
     "expr": "sum by(friendly_name) (hass_climate_target_temperature_low_celsius{friendly_name=\"Living Room\"}) * 1.8 + 32",
     "legendFormat": "Target temp low"
    },
    {
     "expr": "sum by(friendly_name) (hass_climate_action{action=\"cooling\", friendly_name=\"Living Room\"})",
     "legendFormat": "Cooling"
    },
    {
     "expr": "sum by(friendly_name) (hass_climate_action{action=\"heating\", friendly_name=\"Living Room\"})",
     "legendFormat": "Heating"
    }
   ]
  },
  {
   "title": "Upstairs thermostat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (hass_sensor_temperature_celsius{friendly_name=\"Upstairs Temperature\"}) * 1.8 + 32",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "hass_sensor_temperature_celsius{friendly_name=\"OpenWeatherMap Temperature\"} * 1.8 + 32",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "sum by(friendly_name) (hass_climate_target_temperature_high_celsius{friendly_name=\"Upstairs\"}) * 1.8 + 32",
     "legendFormat": "Target temp high"
    },
    {
     "expr": "sum by(friendly_name) (hass_climate_target_temperature_low_celsius{friendly_name=\"Upstairs\"}) * 1.8 + 32",
     "legendFormat": "Target temp low"
    },
    {
     "expr": "sum by(friendly_name) (hass_climate_action{action=\"cooling\", friendly_name=\"Upstairs\"})",
     "legendFormat": "Cooling"
    },
    {
     "expr": "sum by(friendly_name) (hass_climate_action{action=\"heating\", friendly_name=\"Upstairs\"})",
     "legendFormat": "Heating"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (hass_sensor_humidity_percent)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}