{
 "title": "System",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (cpu) (\n  sum without (mode) (\n    rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[1m])\n  )\n)",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (sensor, instance) ( node_hwmon_temp_celsius ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) ((node_filesystem_size_bytes{device=\"/dev/sda1\"} - node_filesystem_avail_bytes{device=\"/dev/sda1\"}) / node_filesystem_size_bytes{device=\"/dev/sda1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (cpu) (\n  sum without (mode) (\n    rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[1m])\n  )\n)",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without (instance) ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum without (instance) (node_hwmon_temp_celsius)",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without (instance) (node_filesystem_size_bytes{device=\"/dev/sda1\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum without (instance) (node_filesystem_avail_bytes{device=\"/dev/sda1\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum without (instance) (node_filesystem_size_bytes{device=\"/dev/sda1\"} - node_filesystem_avail_bytes{device=\"/dev/sda1\"})",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}